version: '3.8'

services:
  db:
    build:
      context: ./docker/sql-server
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - planmp-network

networks:
  planmp-network:
    driver: bridge

volumes:
  sqlserver_data: